# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Site CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Publish Page
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Deploy to gh-pages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: deploy

